name: Build PHAR

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer, box

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build PHAR
        run: box compile

      - name: Upload PHAR to Release
        uses: softprops/action-gh-release@v1
        with:
          files: deployer.phar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}